/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Message extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3576532372712504166L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Message\",\"namespace\":\"com.example.avro\",\"fields\":[{\"name\":\"message_type\",\"type\":\"string\"},{\"name\":\"date\",\"type\":\"string\"},{\"name\":\"message_id\",\"type\":\"string\"},{\"name\":\"creation_time\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Message> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Message> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Message> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Message> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Message> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Message to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Message from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Message instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Message fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence message_type;
  private java.lang.CharSequence date;
  private java.lang.CharSequence message_id;
  private long creation_time;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Message() {}

  /**
   * All-args constructor.
   * @param message_type The new value for message_type
   * @param date The new value for date
   * @param message_id The new value for message_id
   * @param creation_time The new value for creation_time
   */
  public Message(java.lang.CharSequence message_type, java.lang.CharSequence date, java.lang.CharSequence message_id, java.lang.Long creation_time) {
    this.message_type = message_type;
    this.date = date;
    this.message_id = message_id;
    this.creation_time = creation_time;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message_type;
    case 1: return date;
    case 2: return message_id;
    case 3: return creation_time;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message_type = (java.lang.CharSequence)value$; break;
    case 1: date = (java.lang.CharSequence)value$; break;
    case 2: message_id = (java.lang.CharSequence)value$; break;
    case 3: creation_time = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'message_type' field.
   * @return The value of the 'message_type' field.
   */
  public java.lang.CharSequence getMessageType() {
    return message_type;
  }


  /**
   * Sets the value of the 'message_type' field.
   * @param value the value to set.
   */
  public void setMessageType(java.lang.CharSequence value) {
    this.message_type = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.lang.CharSequence getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.CharSequence value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'message_id' field.
   * @return The value of the 'message_id' field.
   */
  public java.lang.CharSequence getMessageId() {
    return message_id;
  }


  /**
   * Sets the value of the 'message_id' field.
   * @param value the value to set.
   */
  public void setMessageId(java.lang.CharSequence value) {
    this.message_id = value;
  }

  /**
   * Gets the value of the 'creation_time' field.
   * @return The value of the 'creation_time' field.
   */
  public long getCreationTime() {
    return creation_time;
  }


  /**
   * Sets the value of the 'creation_time' field.
   * @param value the value to set.
   */
  public void setCreationTime(long value) {
    this.creation_time = value;
  }

  /**
   * Creates a new Message RecordBuilder.
   * @return A new Message RecordBuilder
   */
  public static com.example.avro.Message.Builder newBuilder() {
    return new com.example.avro.Message.Builder();
  }

  /**
   * Creates a new Message RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Message RecordBuilder
   */
  public static com.example.avro.Message.Builder newBuilder(com.example.avro.Message.Builder other) {
    if (other == null) {
      return new com.example.avro.Message.Builder();
    } else {
      return new com.example.avro.Message.Builder(other);
    }
  }

  /**
   * Creates a new Message RecordBuilder by copying an existing Message instance.
   * @param other The existing instance to copy.
   * @return A new Message RecordBuilder
   */
  public static com.example.avro.Message.Builder newBuilder(com.example.avro.Message other) {
    if (other == null) {
      return new com.example.avro.Message.Builder();
    } else {
      return new com.example.avro.Message.Builder(other);
    }
  }

  /**
   * RecordBuilder for Message instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Message>
    implements org.apache.avro.data.RecordBuilder<Message> {

    private java.lang.CharSequence message_type;
    private java.lang.CharSequence date;
    private java.lang.CharSequence message_id;
    private long creation_time;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.avro.Message.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message_type)) {
        this.message_type = data().deepCopy(fields()[0].schema(), other.message_type);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.message_id)) {
        this.message_id = data().deepCopy(fields()[2].schema(), other.message_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.creation_time)) {
        this.creation_time = data().deepCopy(fields()[3].schema(), other.creation_time);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Message instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.avro.Message other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.message_type)) {
        this.message_type = data().deepCopy(fields()[0].schema(), other.message_type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.message_id)) {
        this.message_id = data().deepCopy(fields()[2].schema(), other.message_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.creation_time)) {
        this.creation_time = data().deepCopy(fields()[3].schema(), other.creation_time);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'message_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageType() {
      return message_type;
    }


    /**
      * Sets the value of the 'message_type' field.
      * @param value The value of 'message_type'.
      * @return This builder.
      */
    public com.example.avro.Message.Builder setMessageType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.message_type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'message_type' field has been set.
      * @return True if the 'message_type' field has been set, false otherwise.
      */
    public boolean hasMessageType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'message_type' field.
      * @return This builder.
      */
    public com.example.avro.Message.Builder clearMessageType() {
      message_type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.lang.CharSequence getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.example.avro.Message.Builder setDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.date = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.example.avro.Message.Builder clearDate() {
      date = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'message_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessageId() {
      return message_id;
    }


    /**
      * Sets the value of the 'message_id' field.
      * @param value The value of 'message_id'.
      * @return This builder.
      */
    public com.example.avro.Message.Builder setMessageId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.message_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'message_id' field has been set.
      * @return True if the 'message_id' field has been set, false otherwise.
      */
    public boolean hasMessageId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'message_id' field.
      * @return This builder.
      */
    public com.example.avro.Message.Builder clearMessageId() {
      message_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'creation_time' field.
      * @return The value.
      */
    public long getCreationTime() {
      return creation_time;
    }


    /**
      * Sets the value of the 'creation_time' field.
      * @param value The value of 'creation_time'.
      * @return This builder.
      */
    public com.example.avro.Message.Builder setCreationTime(long value) {
      validate(fields()[3], value);
      this.creation_time = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'creation_time' field has been set.
      * @return True if the 'creation_time' field has been set, false otherwise.
      */
    public boolean hasCreationTime() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'creation_time' field.
      * @return This builder.
      */
    public com.example.avro.Message.Builder clearCreationTime() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Message build() {
      try {
        Message record = new Message();
        record.message_type = fieldSetFlags()[0] ? this.message_type : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.date = fieldSetFlags()[1] ? this.date : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.message_id = fieldSetFlags()[2] ? this.message_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.creation_time = fieldSetFlags()[3] ? this.creation_time : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Message>
    WRITER$ = (org.apache.avro.io.DatumWriter<Message>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Message>
    READER$ = (org.apache.avro.io.DatumReader<Message>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.message_type);

    out.writeString(this.date);

    out.writeString(this.message_id);

    out.writeLong(this.creation_time);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.message_type = in.readString(this.message_type instanceof Utf8 ? (Utf8)this.message_type : null);

      this.date = in.readString(this.date instanceof Utf8 ? (Utf8)this.date : null);

      this.message_id = in.readString(this.message_id instanceof Utf8 ? (Utf8)this.message_id : null);

      this.creation_time = in.readLong();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.message_type = in.readString(this.message_type instanceof Utf8 ? (Utf8)this.message_type : null);
          break;

        case 1:
          this.date = in.readString(this.date instanceof Utf8 ? (Utf8)this.date : null);
          break;

        case 2:
          this.message_id = in.readString(this.message_id instanceof Utf8 ? (Utf8)this.message_id : null);
          break;

        case 3:
          this.creation_time = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










